/* MTI_DPI */

/*
 * Copyright 2002-2020 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linuxaloem'
 */
#ifndef INCLUDED_UARTDPI
#define INCLUDED_UARTDPI

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
uartdpi_can_read(
    void* ctx);

DPI_LINK_DECL DPI_DLLESPEC
void
uartdpi_close(
    void* ctx);

DPI_LINK_DECL DPI_DLLESPEC
void*
uartdpi_create(
    const char* name,
    const char* log_file_path);

DPI_LINK_DECL DPI_DLLESPEC
char
uartdpi_read(
    void* ctx);

DPI_LINK_DECL DPI_DLLESPEC
void
uartdpi_write(
    void* ctx,
    int data);

#endif 
